"""SSR detection engine for GWICO-SSR."""

from gwico_ssr.ssr.detector import (
    DETECTOR_VERSION,
    DetectionResult,
    DetectorConfig,
    ImperfectionMetadata,
    ImperfectionThresholds,
    SSRHit,
    SSRThresholds,
    apply_compound_detection_to_result,
    detect_imperfect_ssrs,
    detect_ssrs,
    detect_ssrs_from_fasta,
)
from gwico_ssr.ssr.imperfection import (
    AlignmentResult,
    IndelEvent,
    align_motif_to_region,
    calculate_imperfection_pct,
    count_substitutions_in_alignment,
    find_indels,
    generate_alignment_text,
)
from gwico_ssr.ssr.motif import (
    all_rotations,
    canonicalize_motif,
    determine_strand,
    is_sub_repeat,
    reverse_complement,
)
from gwico_ssr.ssr.compound import (
    CompoundHit,
    StandardizationLevel,
    build_compound_hit,
    detect_compound_ssrs,
    find_compound_chains,
    mark_compound_components,
    standardize_motif,
)

__all__ = [
    "DETECTOR_VERSION",
    "DetectionResult",
    "DetectorConfig",
    "ImperfectionMetadata",
    "ImperfectionThresholds",
    "SSRHit",
    "SSRThresholds",
    "AlignmentResult",
    "IndelEvent",
    "all_rotations",
    "align_motif_to_region",
    "apply_compound_detection_to_result",
    "build_compound_hit",
    "calculate_imperfection_pct",
    "canonicalize_motif",
    "CompoundHit",
    "count_substitutions_in_alignment",
    "detect_compound_ssrs",
    "detect_imperfect_ssrs",
    "detect_ssrs",
    "detect_ssrs_from_fasta",
    "determine_strand",
    "find_compound_chains",
    "find_indels",
    "generate_alignment_text",
    "is_sub_repeat",
    "mark_compound_components",
    "reverse_complement",
    "StandardizationLevel",
    "standardize_motif",
]