"""Statistical analysis layer for GWICO-SSR."""

from gwico_ssr.analysis.statistics import (
    AnalysisResult,
    AnalysisSuite,
    base_composition_test,
    chi_square_gene_country,
    chi_square_motif_country,
    correlation_gc_ssr,
    correlation_length_ssr,
    kruskal_wallis_by_country,
    run_all_analyses,
    shannon_entropy_by_country,
    shannon_entropy_motifs,
)
from gwico_ssr.analysis.temporal import (
    DatePrecision,
    TimeBin,
    TemporalSummary,
    parse_date_string,
    normalize_date_to_precision,
    bin_id_from_date,
    create_time_bins,
    get_date_range_for_field,
    query_accessions_in_time_bin,
    query_temporal_ssr_metrics,
    compute_temporal_summary,
)
from gwico_ssr.analysis.lineage import (
    LineageSource,
    LineageAssignment,
    LineageSummary,
    LineageReport,
    ingest_pango_csv,
    ingest_nextstrain_json,
    get_lineage_for_accession,
    audit_lineage_mapping,
    compute_ssr_metrics_by_lineage,
    store_lineage_metrics,
)
from gwico_ssr.phylo import (
    Tree,
    TreeNode,
    TreeSource,
    TreeMapping,
    TreeCladeMetrics,
    TreeMappingReport,
    parse_newick_file,
    validate_tree_structure,
    ingest_newick_tree,
    map_accessions_to_tips,
    compute_ssr_metrics_by_clade,
    store_tree_metrics,
)
from gwico_ssr.analysis.clustering import (
    FeatureMatrixGenerator,
    ClusteringPreprocessor,
    ClusteringAnalysis,
    ClusteringResult,
    ClusterAssignment,
    clusters_by_lineage,
    clusters_by_geography,
)

__all__ = [
    # Statistics
    "AnalysisResult",
    "AnalysisSuite",
    "base_composition_test",
    "chi_square_gene_country",
    "chi_square_motif_country",
    "correlation_gc_ssr",
    "correlation_length_ssr",
    "kruskal_wallis_by_country",
    "run_all_analyses",
    "shannon_entropy_by_country",
    "shannon_entropy_motifs",
    # Temporal
    "DatePrecision",
    "TimeBin",
    "TemporalSummary",
    "parse_date_string",
    "normalize_date_to_precision",
    "bin_id_from_date",
    "create_time_bins",
    "get_date_range_for_field",
    "query_accessions_in_time_bin",
    "query_temporal_ssr_metrics",
    "compute_temporal_summary",
    # Lineage
    "LineageSource",
    "LineageAssignment",
    "LineageSummary",
    "LineageReport",
    "ingest_pango_csv",
    "ingest_nextstrain_json",
    "get_lineage_for_accession",
    "audit_lineage_mapping",
    "compute_ssr_metrics_by_lineage",
    "store_lineage_metrics",
    # Phylogenetic (Chunk 11)
    "Tree",
    "TreeNode",
    "TreeSource",
    "TreeMapping",
    "TreeCladeMetrics",
    "TreeMappingReport",
    "parse_newick_file",
    "validate_tree_structure",
    "ingest_newick_tree",
    "map_accessions_to_tips",
    "compute_ssr_metrics_by_clade",
    "store_tree_metrics",
    # Clustering (Chunk 13)
    "FeatureMatrixGenerator",
    "ClusteringPreprocessor",
    "ClusteringAnalysis",
    "ClusteringResult",
    "ClusterAssignment",
    "clusters_by_lineage",
    "clusters_by_geography",
]
